#!/bin/bash
exec > /tmp/debug-my-script.txt 2>&1

PROJECT_PATH=/opt/sites/appdirectory/project
export PYTHONPATH=/opt/sites/appdirectory
export DJANGO_SETTINGS_MODULE=project.settings

function usage {
	echo 'usage: appdirectory [start|stop|restart]'
}

function start {
	#start gunicorn
	gunicorn_django $PROJECT_PATH/settings.py -c $PROJECT_PATH/gunicorn.conf.py &
	pid=$!
	echo $pid > $PROJECT_PATH/gunicorn.pid
}

function stop {
	pid=$(cat < $PROJECT_PATH/gunicorn.pid)
	kill -TERM $pid
}

function restart {
	pid=$(cat < $PROJECT_PATH/gunicorn.pid)
	kill -HUP $pid
}


if [ $# -lt 1 ]
then
	usage
	exit 1;
fi

case $1 in
	'start') start;;
	'stop') stop;;
	'restart') restart;;
	*) usage;;
esac

exit 0